### ISSUE TITLE
com.segment.analytics.android.integrations.firebase.FirebaseIntegration.makeKey(FirebaseIntegration.java:192) error

### ISSUE THREAD

**Issue by tugcekeser** [segment-integrations/analytics-android-integration-firebase#13]
Hi,
I am getting following error  from a segment class when I run the app. But, this is happening only one of the developers' laptop. Do you know what it is related to?

Thank you!

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
       at com.segment.analytics.android.integrations.firebase.FirebaseIntegration.makeKey(FirebaseIntegration.java:192)
       at com.segment.analytics.android.integrations.firebase.FirebaseIntegration.formatProperties(FirebaseIntegration.java:172)
       at com.segment.analytics.android.integrations.firebase.FirebaseIntegration.track(FirebaseIntegration.java:155)
       at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:176)
       at com.segment.analytics.Analytics.performRun(Analytics.java:1464)
       at com.segment.analytics.Analytics$10.run(Analytics.java:825)

**Comment by prayansh** [comment]
This is probably due to the value in the property list being `null`. I would recheck the scenario this is being run with and ensure no nulls are being passed around. Please reopen if that is not the case :)
