### ISSUE TITLE
App crash: TransactionTooLargeException

### ISSUE THREAD

**Issue by landcy** [segment-integrations/analytics-android-integration-firebase#22]
In my app, it’s easy to crash in device [LG G3， Android 5.0.1]. Once occur, it will keep crash in any screen.

Follow is crash stack:
```

java.lang.RuntimeException: Package manager has died
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:311)
	at com.b.a.a.a.a.a.onActivityResumed(FirebaseIntegration.java:117)
	at com.b.a.i$8.a(IntegrationOperation.java:73)
	at com.b.a.a.b(Analytics.java:1311)
	at com.b.a.a$7$1.run(Analytics.java:389)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: android.os.TransactionTooLargeException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:496)
	at android.content.pm.IPackageManager$Stub$Proxy.getActivityInfo(IPackageManager.java:1992)
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:306)
	... 12 more
```

**Comment by prayansh** [comment]
Hi! this should have been fixed via this PR https://github.com/segmentio/analytics-android/pull/749. Please reopen the issue if you are still experiencing the issue :)
