### ISSUE TITLE
Android Gradle Plugin v3.5.0 causes runtime Fatal Exception

### ISSUE THREAD

**Issue by CorwinJV** [segment-integrations/analytics-android-integration-firebase#23]
When I use segment analytics firebase integration with Android Gradle Plugin v3.5.0, I get a runtime crash every time accessing a gms error code string. 

Firebase seems to work by itself.

`java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f150009`
[Full error log here](https://pastebin.com/wcfsqLzZ)

My workaround for this is to downgrade to android gradle plugin 3.4.1

**Comment by Hospes** [comment]
Yeah the same for me I'm using `3.5.1`
Also you could downgrade lib version to `1.2.0` and use latest android gradle plugin without any problem.

**Comment by jensfrandsen** [comment]
Any news here? We also had to downgrade our gradle plugin...

**Comment by ujjawalgarg** [comment]
Using `@aar` version of the dependency fixed it for us.

e.g.
`implementation "com.segment.analytics.android.integrations:firebase:1.4.0@aar"`

**Comment by sjchmiela** [comment]
FWIW instead of downgrading the Android Gradle plugin, I have downgraded the Google Services plugin (to 3.2.1) — this too let me fix the problem.

I'm not sure, but `@aar` may drop dependency on transitive dependencies, so otherwise-installed `com.google.firebase:…` packages will not be installed (which, if you don't depend on them yourself, may be a bad thing, I think).

**Comment by mwajeeh** [comment]
I keep getting this on versions above 1.2.0:
```
 java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f150009
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f150009
        at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:263)
        at android.content.res.Resources.getResourcePackageName(Resources.java:1970)
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:5)
        at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@19.3.0:156)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:244)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

```

**Comment by Aditya94A** [comment]
I just spent an hour unwrangling every firebase related dependency in my project and read about a dozen stackoverflow rabbit holes that lead nowhere before finding this issue.

That is all. They say sharing reduces pain.

@brennan Please prioritize a fix for this.

**Comment by sergpetrov** [comment]
I faced the same problem. Please, fix it as soon as possible.

**Comment by omgithubdev** [comment]
Faced the same problem. Downgrading version to `1.2.0` helped.
Is there a solution for this with the latest version?

**Comment by Hospes** [comment]
it feels like devs don't care about it :D

**Comment by omgithubdev** [comment]
Using @aar version fixed the issue.

e.g.
implementation "com.segment.analytics.android.integrations:firebase:2.1.0@aar"

**Comment by prayansh** [comment]
Hi All! looks like importing the project with the `@aar` classifier fixes this issue. Closing this out. 
Feel free to reopen if that does not work for you
